class GlobalVar:
     currentPage = None
     api_url = None
     api_dict = {}
     featureFilePath = None
     vpn = {}
     vlan = {}
     device = {}
     Device = {}
     editLANInterface = {}
     afterEditingLANInterface = {}
     access_token = None
     response_codes = {}
     failCounter = 0
     response = None
     requestId = None
     testParams = {}
     testComponent = None
     request_ID = {}
     docId = {}
     reqId = None
     tempVal= None
     baseTest = None
     param = {}
     ServiceParams={}
     sshInfo = {}
     uuid = {}
     binded = None
     vrf_section_content = {}
     regex_pattern =  None
     test_case = None
     current_config = {}
     scenarioStatus = None
     webhookServer = None
     callbackValue = {}
     ie_header = {}
     biFailCounter = 0
     failTest = []
     featureCount = 0
     node = ''
     reason = None
     reqId=''
     connection = None
     connection = None
     requestType = ''
     state = None
     eventType=None
     customer = {}
     transactions = {}
     state = {}     
     toast_msg = None
     version= ''
     allure_html_path = None
     allure_json_path = None
     scenario = ""
     in_progress = None
     action = None
     versions = None
     zk = None
     counter = 1
     published_info = {}
     published_payload = {}
     currentStep = None
     consumerValidNode1 = None
     consumerValidNode2 = None
     consumerInvalidNode1 = None
     consumerInvalidNode2 = None
     consumerTerminationPoint1=None
     consumerTerminationPoint2=None
     consumerInvalidTerminationPoint1 = None
     consumerInvalidTerminationPoint2 = None
     db_obj = None
     commit_uuid = None
     commit_request_id = None
     create_request_obj = None
     l2topology_uuid = None
     l2Topology_response = None
     customerId = None